### ISSUE TITLE
Catch StorageException type

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.AzureStoragePersistence#28]
Azure Storage changed from returning a WebException to using a StorageException. This needs to be changed in code to make sure that any logic in exception handlers is executed properly

**Comment by SimonCropp** [comment]
@dbelcham is there any doco about this change from the azure side?

**Comment by SeanFeldman** [comment]
@SimonCropp `WebException` was a part of the 'old' storage model where `TableContext` was used. The 'new' model using `CloudTable` is throwing [`StorageException`](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.storageexception.aspx). 

> is there any doco about this change from the azure side?

![image](https://cloud.githubusercontent.com/assets/1309622/13452150/addbbc04-e002-11e5-9731-6fbf9796e0fb.png)

**Comment by dbelcham** [comment]
@SimonCropp The best I can find is that `StorageException` was introduced in v2.0 of WindowsAzure.Storage. I cannot find any documentation on when some classes started to throw it vs other exceptions.

I discovered the problem when verifying the code with WAS v6.2. A method was explicitly catching `WebException` and nothing else. When WAS threw the exception wasn't caught in our code because it was of type `StorageException`. From what I can tell, all of the information that previously was being used from `WebException` is available in `StorageException.RequestInformation` (e.g. `HTTPStatusCode`)

**Comment by WilliamBZA** [comment]
@dbelcham @SeanFeldman So I've spent a few hours going through the code and I'm not sure if there is any actual work required to close this. I think it may be done...

We catch a `WebException` in `AzureSagaPersister.Get<T>` [(line 89)](https://github.com/Particular/NServiceBus.AzureStoragePersistence/blob/develop/src/NServiceBus.AzureStoragePersistence/SagaPersisters/Azure/AzureSagaPersister.cs#L89), but that already has code to catch a `StorageException` too.

The only other place where we deal with `WebException` is in `TestHelper` in the `CreateTimeoutPersister` [method](https://github.com/Particular/NServiceBus.AzureStoragePersistence/blob/develop/src/NServiceBus.AzureStoragePersistence.ComponentTests/Timeouts/TestHelper.cs#L22). We don't currently have a catch for the `StorageException` here, but the code would simply catch the exception and then throw it since we want that error to bubble up. Add to that, this code is *only* called during test execution.

Is there anything else that you guys think should still be done here? If not, I think this is another one of those that @dbelcham already completed...

**Comment by SeanFeldman** [comment]
Sounds good @WilliamBZA.
@dbelcham will close it if nothing's left. Easy one :)

**Comment by SimonCropp** [comment]
Doesnt that mean most of the webexception code is redundant if it will no longer be thorwn?

**Comment by WilliamBZA** [comment]
@SimonCropp I've been combing through the MSDN docs to try find out and it seems pretty much undocumented everywhere. Seems almost impossible to see what exceptions could be thrown from each method.

It's times like this that I miss Java and checked exceptions...

I'll go through the calls again and decompile to see if I can get some more info out like that

**Comment by SeanFeldman** [comment]
@WilliamBZA this might be an easier way: https://github.com/Azure/azure-storage-net

**Comment by WilliamBZA** [comment]
Much easier @SeanFeldman :smile:
