### ISSUE TITLE
Update Testing

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus.AzureStoragePersistence#31]
- [x] Change ATs from the current package to a suite of Persistence specific tests
- [x] Update Component Tests to cover Sagas and Pub/Sub

**Comment by adamralph** [comment]
Moved into In Progress, because #27

**Comment by dbelcham** [comment]
Wrapped up with the acceptance of #27

**Comment by adamralph** [comment]
@dbelcham fair to classify this as tech debt? /cc @Particular/persistence-maintainers

**Comment by adamralph** [comment]
@dbelcham sorry, one more question. Was this a hard pre-requisite for the v6 launch?

**Comment by SeanFeldman** [comment]
> Was this a hard pre-requisite for the v6 launch?

The classical answer could be "it depends". We've gone with ASP and no tests for so long that underlying primary dependency (Azure storage library) has increased from v4 to v6 and were couldn't even validate what would be broken and what not. Personally, consider it technical debt that we'd need to pay, and the interest would significantly vary based on when we get the cheques book out :)

Lengthy response to answer your questions @adamralph  :)

**Comment by adamralph** [comment]
@SeanFeldman in my view, if the @Particular/azure-maintainers decided that they cannot complete the V6 Launch work with confidence before doing this, then it's perfectly valid to include it as part of that project.

BTW - I'm not sure why the label has disappeared without any evidence but it may be due to the rename this morning, during which PBot conveniently crashed. I'll add it back.
